# Generated by Django 2.2.6 on 2019-10-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
    ]
